# Generated by Django 5.0 on 2023-12-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
